stages:
  - release

.release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    GITLAB_TOKEN: $CI_JOB_TOKEN
    KO_DOCKER_REPO: $CI_REGISTRY_IMAGE
  before_script:
    - echo https://dl-cdn.alpinelinux.org/alpine/edge/testing/ >> /etc/apk/repositories
    - apk update
    - apk add ko
    - ko login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - goreleaser release --clean

release:
  extends: .release
  only:
    - tags

snapshot-release:
  extends: .release
  when: manual
  script:
    - goreleaser release --snapshot --clean