# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

builds:
  - id: binary
    main: ./main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X github.com/yoshino-s/go-framework/common.Version={{.Version}}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"

kos:
  - id: ko-image
    build: binary
    main: .
    ldflags:
      - "-s -w -X github.com/yoshino-s/go-framework/common.Version={{.Version}}"
    platforms:
      - all
    tags:
      - '{{ .Tag }}'
      - '{{ .FullCommit }}'
      - latest
    sbom: spdx
    bare: true
    preserve_import_paths: false
    base_import_paths: false

archives:
  - id: with-version
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
  - id: without-version
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

gitlab_urls:
  api: https://gitlab.yoshino-s.xyz/api/v4/
  download: https://gitlab.yoshino-s.xyz
  # set to true if you want to upload to the Package Registry rather than attachments
  # Only works with GitLab 13.5+
  use_package_registry: true

  # Set this if you set GITLAB_TOKEN to the value of CI_JOB_TOKEN.
  use_job_token: true


changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
