// Code generated by ent, DO NOT EDIT.

package ent

func (ic *IcpCreate) SetIcp(input *Icp) *IcpCreate {
	ic.SetHost(input.Host)
	ic.SetCity(input.City)
	ic.SetProvince(input.Province)
	ic.SetCompany(input.Company)
	ic.SetOwner(input.Owner)
	ic.SetType(input.Type)
	ic.SetHomepage(input.Homepage)
	ic.SetPermit(input.Permit)
	ic.SetWebName(input.WebName)
	ic.SetCreatedAt(input.CreatedAt)
	ic.SetUpdatedAt(input.UpdatedAt)
	return ic
}
