// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IcpsColumns holds the columns for the "icps" table.
	IcpsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "host", Type: field.TypeString, Unique: true},
		{Name: "city", Type: field.TypeString, Nullable: true},
		{Name: "province", Type: field.TypeString, Nullable: true},
		{Name: "company", Type: field.TypeString, Nullable: true},
		{Name: "owner", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeString, Default: "INVALID"},
		{Name: "homepage", Type: field.TypeString, Nullable: true},
		{Name: "permit", Type: field.TypeString, Nullable: true},
		{Name: "web_name", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// IcpsTable holds the schema information for the "icps" table.
	IcpsTable = &schema.Table{
		Name:       "icps",
		Columns:    IcpsColumns,
		PrimaryKey: []*schema.Column{IcpsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IcpsTable,
	}
)

func init() {
}
