// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/yoshino-s/soar-helper/ent/icp"
	"github.com/yoshino-s/soar-helper/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	icpFields := schema.Icp{}.Fields()
	_ = icpFields
	// icpDescType is the schema descriptor for type field.
	icpDescType := icpFields[5].Descriptor()
	// icp.DefaultType holds the default value on creation for the type field.
	icp.DefaultType = icpDescType.Default.(string)
	// icpDescCreatedAt is the schema descriptor for created_at field.
	icpDescCreatedAt := icpFields[9].Descriptor()
	// icp.DefaultCreatedAt holds the default value on creation for the created_at field.
	icp.DefaultCreatedAt = icpDescCreatedAt.Default.(func() time.Time)
	// icpDescUpdatedAt is the schema descriptor for updated_at field.
	icpDescUpdatedAt := icpFields[10].Descriptor()
	// icp.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	icp.DefaultUpdatedAt = icpDescUpdatedAt.Default.(func() time.Time)
	// icp.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	icp.UpdateDefaultUpdatedAt = icpDescUpdatedAt.UpdateDefault.(func() time.Time)
}
