name: Build Base Image

on:
  push:
    branches:
      - main
    paths:
      - 'baseimage/**'
      - .github/workflows/baseimage.yml

permissions:
  packages: write
  id-token: write

jobs:
  apko:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1
      - name: Setup Image Tags
        run: |
          repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/${repo}" >> $GITHUB_ENV
      - uses: distroless/actions/apko-publish@main
        id: apko
        with:
          config: baseimage/apko.yml
          tag: ${IMAGE_NAME}:base-latest
      - name: Cosign
        shell: bash
        run: |
          COSIGN_EXPERIMENTAL=true cosign sign --yes ${{ steps.apko.outputs.digest }}
