name: snapshot

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: ko-build/setup-ko@v0.6
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Ko
        env:
          KO_DEFAULTBASEIMAGE: cgr.dev/chainguard/chromium
        run: |
          ko build --bare --sbom spdx --tags snapshot,${{ github.sha }},$(git describe --tags)
