name: Build snapshot

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: ko-build/setup-ko@v0.6
      - name: Run Ko
        env:
          KO_DEFAULTBASEIMAGE: ghcr.io/${{ github.repository }}:base-latest
        run: |
          ko build --bare --sbom spdx --tags snapshot,${{ github.sha }},$(git describe --tags)
